name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: "Populate auth file with SFDX_URL secret"
        shell: bash
        run: "echo ${{ secrets.sfdxurl}} > ./SFDX_URL_STORE.txt"
      - name: "Authenticate against dev hub"
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: "force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=devhub --setdefaultdevhubusername"
